In [1]:
import os
import dask.dataframe as dd
from dask.distributed import Client
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)


pd_data_dir = "/home/djl34/lab_pd/data"
aso_data_dir = "/home/djl34/lab_pd/aso/data"
KL_data_dir = "/home/djl34/lab_pd/kl/data"
scratch_dir = "/n/scratch3/users/d/djl34"

In [2]:
df = pd.read_csv(pd_data_dir + "/shet_gnomAD_Roulette_0.01cutoff_v2.csv")

In [4]:
df[df["mean_s_het"] > 0.1]

,Gene_symbol,Gene_stable_ID,mean_s_het,s_het_lower95,s_het_upper95,mu,AC,AN_int
0,MED13,ENSG00000108510,1.000000,0.373,1.000,8.600000e-06,0,248737.2802
1,NIPBL,ENSG00000164190,1.000000,0.506,1.000,1.580000e-05,1,250565.9300
2,SMC3,ENSG00000108055,0.941921,0.341,1.000,7.540000e-06,0,251111.6991
3,RSF1,ENSG00000048649,0.909534,0.324,1.000,7.050000e-06,0,250292.8541
4,KDM2A,ENSG00000173120,0.894543,0.316,1.000,6.870000e-06,0,248522.1399
...,...,...,...,...,...,...,...,...
3561,ZNF416,ENSG00000083817,0.100087,0.020,0.381,3.340000e-07,1,251135.4510
3562,ARHGAP32,ENSG00000134909,0.100037,0.064,0.156,7.420000e-06,19,250909.6489
3563,ZNF322,ENSG00000181315,0.100037,0.028,0.310,7.230000e-07,2,240368.8158
3564,COL8A1,ENSG00000144810,0.100015,0.039,0.244,1.470000e-06,4,249614.5610
3565,JPH1,ENSG00000104369,0.100008,0.039,0.244,1.470000e-06,4,248769.4317

In [5]:
df[df["mean_s_het"] < 0.01]

,Gene_symbol,Gene_stable_ID,mean_s_het,s_het_lower95,s_het_upper95,mu,AC,AN_int
14508,ITLN1,ENSG00000179914,0.009996,0.00800,0.01400,1.530000e-06,40,250521.2849
14509,FBXW5,ENSG00000159069,0.009993,0.00800,0.01400,1.620000e-06,40,236313.0933
14510,GALNT3,ENSG00000115339,0.009990,0.00800,0.01300,2.560000e-06,66,250907.1777
14511,GPAT2,ENSG00000186281,0.009990,0.00800,0.01300,2.850000e-06,69,236591.6446
14512,TAS1R2,ENSG00000179002,0.009990,0.00800,0.01400,1.850000e-06,48,250839.4357
...,...,...,...,...,...,...,...,...
17303,GJA10,ENSG00000135355,0.001228,0.00077,0.00198,3.840000e-08,17,232626.5714
17304,KRTAP19-8,ENSG00000206102,0.001209,0.00078,0.00187,4.880000e-08,20,250638.3636
17305,OR5P2,ENSG00000183303,0.001202,0.00080,0.00181,6.290000e-08,23,249442.4667
17306,HBB,ENSG00000244734,0.001060,0.00087,0.00130,3.620000e-07,97,251292.3509
17307,ZNF345,ENSG00000251247,0.000655,0.00046,0.00094,3.580000e-08,30,222711.5000